RIGHT_MOTOR_MASTER_ID = 22
RIGHT_MOTOR_SLAVE_ID = 12
LEFT_MOTOR_MASTER_ID = 28
LEFT_MOTOR_SLAVE_ID = 23
WHEEL_DIAMETER = 6 #inches
WHEEL_BASE = 10 #inches (distance between wheels)
DRIVE_ENCODER_TICKS_PER_REVOLUTION_LEFT = 1000
DRIVE_ENCODER_TICKS_PER_REVOLUTION_RIGHT = 1000

