import math
"""Global constants that are accesed throughout the project"""
LEFT_MOTOR_SLAVE_ID = 28
LEFT_MOTOR_MASTER_ID = 23
RIGHT_MOTOR_SLAVE_ID = 12
RIGHT_MOTOR_MASTER_ID = 22

WHEEL_DIAMETER = 6  # inches
WHEEL_CIRCUMFERENCE = WHEEL_DIAMETER*math.pi  # inches
WHEEL_BASE = 27.75  # inches (distance between wheels)

DRIVE_ENCODER_TICKS_PER_REVOLUTION_LEFT = 4096  # UPDATE
DRIVE_ENCODER_TICKS_PER_REVOLUTION_RIGHT =  4096  # UPDATE

TANK_DRIVE_EXPONENT = 3
